"""Initial migration.

Revision ID: 01c4ffae47e5
Revises: 6e0ebd79271f
Create Date: 2020-10-22 23:57:42.117844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c4ffae47e5'
down_revision = '6e0ebd79271f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comment_book_id'), 'comment', ['book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_book_id'), table_name='comment')
    # ### end Alembic commands ###
