"""empty message

Revision ID: 24a1f0ebb90d
Revises: 51fea902fa63
Create Date: 2020-10-22 17:28:09.014674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a1f0ebb90d'
down_revision = '51fea902fa63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'book_id')
    # ### end Alembic commands ###
