"""empty message

Revision ID: 257c0e4e4bd4
Revises: a23b436833e4
Create Date: 2020-10-25 22:30:01.839757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257c0e4e4bd4'
down_revision = 'a23b436833e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
