"""empty message

Revision ID: 2ef6e871edd0
Revises: 01c4ffae47e5
Create Date: 2020-10-23 13:46:28.619076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ef6e871edd0'
down_revision = '01c4ffae47e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('comment', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('comment', 'created_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created_date', mysql.DATETIME(), nullable=True))
    op.drop_column('comment', 'time_updated')
    op.drop_column('comment', 'time_created')
    # ### end Alembic commands ###
