"""empty message

Revision ID: 396993670342
Revises: 24a1f0ebb90d
Create Date: 2020-10-22 23:04:26.362897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396993670342'
down_revision = '24a1f0ebb90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'book', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_1', 'comment', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###
