"""empty message

Revision ID: a94f3c2afd0d
Revises: 396993670342
Create Date: 2020-10-22 23:19:25.669492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a94f3c2afd0d'
down_revision = '396993670342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
