"""empty message

Revision ID: c018b2059243
Revises: a94f3c2afd0d
Create Date: 2020-10-22 23:21:58.876121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c018b2059243'
down_revision = 'a94f3c2afd0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
