"""empty message

Revision ID: da73f02eb0e6
Revises: c018b2059243
Create Date: 2020-10-22 23:24:36.700413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da73f02eb0e6'
down_revision = 'c018b2059243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
